name: 'GitHub Actions '

on:
  workflow_dispatch:
  #schedule:
    #- cron: '1 */6 * * *'
jobs:
  ddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: 'Set up Python'
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        # timeout-minutes: 360
        run: |
          rm -rf *.csv 
          wget -O IPDBproxy.txt  https://raw.githubusercontent.com/ymyuuu/IPDB/main/BestProxy/proxy.txt
          cat IPDBproxy.txt >> ip.txt 
          rm -rf IPDBproxy.txt
          chmod +x ./iptest.sh
          bash ./iptest.sh -t 100
          python ./df_sorted.py
          python ./create_proxyip.py
          rm -rf realip*.txt oldrealip/ oldcsv/
          rm -rf *-ip.txt.csv*
          rm -rf ip.txt
      - name: 'run dnscf'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_DNS_NAME: ${{ secrets.CF_DNS_NAME }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python dnscf.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}